"""initial schema — 20 tables

Revision ID: 35fe10bd4a75
Revises:
Create Date: 2026-07-30 14:03:31.881437+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision: str = "35fe10bd4a75"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_snapshots",
        sa.Column("snapshot_type", sa.String(length=50), nullable=False),
        sa.Column("snapshot_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_jobs", sa.Integer(), nullable=False),
        sa.Column("new_jobs", sa.Integer(), nullable=False),
        sa.Column("active_jobs", sa.Integer(), nullable=False),
        sa.Column("remote_jobs", sa.Integer(), nullable=False),
        sa.Column("total_matches", sa.Integer(), nullable=False),
        sa.Column("high_matches", sa.Integer(), nullable=False),
        sa.Column("average_match_score", sa.Float(), nullable=True),
        sa.Column("total_applications", sa.Integer(), nullable=False),
        sa.Column("interviews", sa.Integer(), nullable=False),
        sa.Column("offers", sa.Integer(), nullable=False),
        sa.Column("rejections", sa.Integer(), nullable=False),
        sa.Column("top_companies", sa.JSON(), nullable=True),
        sa.Column("top_skills", sa.JSON(), nullable=True),
        sa.Column("skill_gaps", sa.JSON(), nullable=True),
        sa.Column("salary_distribution", sa.JSON(), nullable=True),
        sa.Column("source_performance", sa.JSON(), nullable=True),
        sa.Column("location_distribution", sa.JSON(), nullable=True),
        sa.Column("hiring_trends", sa.JSON(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analytics_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analytics_snapshots_snapshot_date"), ["snapshot_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analytics_snapshots_snapshot_type"), ["snapshot_type"], unique=False
        )

    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("website", sa.String(length=1000), nullable=True),
        sa.Column("industry", sa.String(length=255), nullable=True),
        sa.Column("company_type", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.String(length=1000), nullable=True),
        sa.Column("headquarters", sa.String(length=255), nullable=True),
        sa.Column("employee_count", sa.String(length=50), nullable=True),
        sa.Column("known_tech_stack", sa.JSON(), nullable=True),
        sa.Column("remote_friendly", sa.Boolean(), nullable=True),
        sa.Column("average_salary", sa.Integer(), nullable=True),
        sa.Column("hiring_frequency", sa.String(length=50), nullable=True),
        sa.Column("average_match_score", sa.Float(), nullable=True),
        sa.Column("total_jobs_found", sa.Integer(), nullable=False),
        sa.Column("total_applications", sa.Integer(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("is_blacklisted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_companies_is_blacklisted"), ["is_blacklisted"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_companies_is_favorite"), ["is_favorite"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_companies_normalized_name"), ["normalized_name"], unique=True
        )

    op.create_table(
        "llm_caches",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("resume_version_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("response_structured", sa.JSON(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_hash", "task_type", "resume_version_id", name="uq_llm_cache_key"
        ),
    )
    with op.batch_alter_table("llm_caches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_caches_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_llm_caches_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_caches_task_type"), ["task_type"], unique=False)

    op.create_table(
        "reports",
        sa.Column("report_type", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("total_jobs", sa.Integer(), nullable=False),
        sa.Column("total_matches", sa.Integer(), nullable=False),
        sa.Column("worksheets", sa.JSON(), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_generated_at"), ["generated_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_report_type"), ["report_type"], unique=False)

    op.create_table(
        "search_checkpoints",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("keyword", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("last_page", sa.Integer(), nullable=False),
        sa.Column("total_results", sa.Integer(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("cursor", sa.String(length=1000), nullable=True),
        sa.Column("state_data", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "keyword", "location", name="uq_search_checkpoint"),
    )
    with op.batch_alter_table("search_checkpoints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_checkpoints_provider"), ["provider"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "jobs",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("responsibilities", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("is_remote", sa.Boolean(), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=10), nullable=True),
        sa.Column("salary_period", sa.String(length=20), nullable=True),
        sa.Column("experience_min", sa.Integer(), nullable=True),
        sa.Column("experience_max", sa.Integer(), nullable=True),
        sa.Column("seniority_level", sa.String(length=50), nullable=True),
        sa.Column("employment_type", sa.String(length=50), nullable=True),
        sa.Column("posting_url", sa.String(length=2000), nullable=True),
        sa.Column("apply_url", sa.String(length=2000), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("tech_stack", sa.JSON(), nullable=True),
        sa.Column("structured_data", sa.JSON(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("duplicate_of_id", sa.String(length=36), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("rule_score", sa.Float(), nullable=True),
        sa.Column("embedding_score", sa.Float(), nullable=True),
        sa.Column("llm_score_adjustment", sa.Float(), nullable=True),
        sa.Column("match_explanation", sa.Text(), nullable=True),
        sa.Column("missing_skills", sa.JSON(), nullable=True),
        sa.Column("apply_recommendation", sa.String(length=20), nullable=True),
        sa.Column("matched_resume_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["duplicate_of_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_country"), ["country"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_external_id"), ["external_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_is_remote"), ["is_remote"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_location"), ["location"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_match_score"), ["match_score"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_posted_at"), ["posted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_title"), ["title"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.String(length=36), nullable=True),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("is_sent", sa.Boolean(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_dedup_key"), ["dedup_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_notifications_is_sent"), ["is_sent"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notifications_notification_type"), ["notification_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "recruiters",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("linkedin_url", sa.String(length=1000), nullable=True),
        sa.Column("department", sa.String(length=255), nullable=True),
        sa.Column("last_contacted_at", sa.String(length=50), nullable=True),
        sa.Column("response_status", sa.String(length=50), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recruiters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recruiters_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recruiters_created_at"), ["created_at"], unique=False)

    op.create_table(
        "resume_versions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("total_experience_years", sa.Float(), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resume_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resume_versions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resume_versions_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_resume_versions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("preferred_roles", sa.JSON(), nullable=True),
        sa.Column("preferred_locations", sa.JSON(), nullable=True),
        sa.Column("preferred_companies", sa.JSON(), nullable=True),
        sa.Column("blacklisted_companies", sa.JSON(), nullable=True),
        sa.Column("preferred_technologies", sa.JSON(), nullable=True),
        sa.Column("blacklisted_keywords", sa.JSON(), nullable=True),
        sa.Column("minimum_salary", sa.Integer(), nullable=True),
        sa.Column("maximum_experience", sa.Integer(), nullable=True),
        sa.Column("notification_threshold", sa.Integer(), nullable=False),
        sa.Column("search_frequency_hours", sa.Integer(), nullable=False),
        sa.Column("active_resume_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_preferences_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_preferences_user_id"), ["user_id"], unique=True)

    op.create_table(
        "applications",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("current_stage", sa.String(length=50), nullable=False),
        sa.Column("application_url", sa.String(length=2000), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resume_version_id", sa.String(length=36), nullable=True),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("recruiter_name", sa.String(length=255), nullable=True),
        sa.Column("recruiter_email", sa.String(length=255), nullable=True),
        sa.Column("next_interview_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("offer_amount", sa.String(length=100), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_applications_current_stage"), ["current_stage"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_applications_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_id", name="uq_user_bookmark"),
    )
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookmarks_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookmarks_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookmarks_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookmarks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "job_embeddings",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_embeddings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_embeddings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_job_embeddings_job_id"), ["job_id"], unique=True)

    op.create_table(
        "job_skills",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("skill_name", sa.String(length=255), nullable=False),
        sa.Column("skill_category", sa.String(length=100), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "skill_name", name="uq_job_skill"),
    )
    with op.batch_alter_table("job_skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_skills_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_skills_skill_name"), ["skill_name"], unique=False)

    op.create_table(
        "job_sources",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("source_job_id", sa.String(length=255), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "source_type", name="uq_job_source"),
    )
    with op.batch_alter_table("job_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_sources_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_sources_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_job_sources_source_type"), ["source_type"], unique=False
        )

    op.create_table(
        "resume_embeddings",
        sa.Column("resume_version_id", sa.String(length=36), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["resume_version_id"], ["resume_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resume_embeddings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resume_embeddings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resume_embeddings_resume_version_id"), ["resume_version_id"], unique=True
        )

    op.create_table(
        "resume_skills",
        sa.Column("resume_version_id", sa.String(length=36), nullable=False),
        sa.Column("skill_name", sa.String(length=255), nullable=False),
        sa.Column("skill_category", sa.String(length=100), nullable=True),
        sa.Column("proficiency_level", sa.String(length=50), nullable=True),
        sa.Column("years_of_experience", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["resume_version_id"], ["resume_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resume_version_id", "skill_name", name="uq_resume_skill"),
    )
    with op.batch_alter_table("resume_skills", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resume_skills_resume_version_id"), ["resume_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resume_skills_skill_name"), ["skill_name"], unique=False
        )

    op.create_table(
        "application_stage_histories",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("from_stage", sa.String(length=50), nullable=True),
        sa.Column("to_stage", sa.String(length=50), nullable=False),
        sa.Column(
            "transitioned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("application_stage_histories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_stage_histories_application_id"),
            ["application_id"],
            unique=False,
        )

    op.create_table(
        "bookmark_tags",
        sa.Column("bookmark_id", sa.String(length=36), nullable=False),
        sa.Column("tag_name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["bookmark_id"], ["bookmarks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bookmark_id", "tag_name", name="uq_bookmark_tag"),
    )
    with op.batch_alter_table("bookmark_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bookmark_tags_bookmark_id"), ["bookmark_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_bookmark_tags_tag_name"), ["tag_name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookmark_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookmark_tags_tag_name"))
        batch_op.drop_index(batch_op.f("ix_bookmark_tags_bookmark_id"))

    op.drop_table("bookmark_tags")
    with op.batch_alter_table("application_stage_histories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_stage_histories_application_id"))

    op.drop_table("application_stage_histories")
    with op.batch_alter_table("resume_skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_skills_skill_name"))
        batch_op.drop_index(batch_op.f("ix_resume_skills_resume_version_id"))

    op.drop_table("resume_skills")
    with op.batch_alter_table("resume_embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_embeddings_resume_version_id"))
        batch_op.drop_index(batch_op.f("ix_resume_embeddings_created_at"))

    op.drop_table("resume_embeddings")
    with op.batch_alter_table("job_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_sources_source_type"))
        batch_op.drop_index(batch_op.f("ix_job_sources_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_sources_created_at"))

    op.drop_table("job_sources")
    with op.batch_alter_table("job_skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_skills_skill_name"))
        batch_op.drop_index(batch_op.f("ix_job_skills_job_id"))

    op.drop_table("job_skills")
    with op.batch_alter_table("job_embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_embeddings_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_embeddings_created_at"))

    op.drop_table("job_embeddings")
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookmarks_user_id"))
        batch_op.drop_index(batch_op.f("ix_bookmarks_priority"))
        batch_op.drop_index(batch_op.f("ix_bookmarks_job_id"))
        batch_op.drop_index(batch_op.f("ix_bookmarks_created_at"))

    op.drop_table("bookmarks")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_user_id"))
        batch_op.drop_index(batch_op.f("ix_applications_job_id"))
        batch_op.drop_index(batch_op.f("ix_applications_current_stage"))
        batch_op.drop_index(batch_op.f("ix_applications_created_at"))

    op.drop_table("applications")
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_preferences_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_preferences_created_at"))

    op.drop_table("user_preferences")
    with op.batch_alter_table("resume_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_versions_user_id"))
        batch_op.drop_index(batch_op.f("ix_resume_versions_is_active"))
        batch_op.drop_index(batch_op.f("ix_resume_versions_created_at"))

    op.drop_table("resume_versions")
    with op.batch_alter_table("recruiters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recruiters_created_at"))
        batch_op.drop_index(batch_op.f("ix_recruiters_company_id"))

    op.drop_table("recruiters")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_notification_type"))
        batch_op.drop_index(batch_op.f("ix_notifications_is_sent"))
        batch_op.drop_index(batch_op.f("ix_notifications_dedup_key"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_title"))
        batch_op.drop_index(batch_op.f("ix_jobs_posted_at"))
        batch_op.drop_index(batch_op.f("ix_jobs_match_score"))
        batch_op.drop_index(batch_op.f("ix_jobs_location"))
        batch_op.drop_index(batch_op.f("ix_jobs_is_remote"))
        batch_op.drop_index(batch_op.f("ix_jobs_is_active"))
        batch_op.drop_index(batch_op.f("ix_jobs_external_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_created_at"))
        batch_op.drop_index(batch_op.f("ix_jobs_country"))
        batch_op.drop_index(batch_op.f("ix_jobs_content_hash"))
        batch_op.drop_index(batch_op.f("ix_jobs_company_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    with op.batch_alter_table("search_checkpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_checkpoints_provider"))

    op.drop_table("search_checkpoints")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_report_type"))
        batch_op.drop_index(batch_op.f("ix_reports_generated_at"))

    op.drop_table("reports")
    with op.batch_alter_table("llm_caches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_caches_task_type"))
        batch_op.drop_index(batch_op.f("ix_llm_caches_created_at"))
        batch_op.drop_index(batch_op.f("ix_llm_caches_content_hash"))

    op.drop_table("llm_caches")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_normalized_name"))
        batch_op.drop_index(batch_op.f("ix_companies_name"))
        batch_op.drop_index(batch_op.f("ix_companies_is_favorite"))
        batch_op.drop_index(batch_op.f("ix_companies_is_blacklisted"))
        batch_op.drop_index(batch_op.f("ix_companies_created_at"))

    op.drop_table("companies")
    with op.batch_alter_table("analytics_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_snapshots_snapshot_type"))
        batch_op.drop_index(batch_op.f("ix_analytics_snapshots_snapshot_date"))

    op.drop_table("analytics_snapshots")
    # ### end Alembic commands ###
